# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
                ('image_url', models.URLField()),
                ('contact_info', models.CharField(max_length=30, null=True)),
                ('performance_copyright', models.CharField(max_length=30)),
            ],
        ),
    ]
