# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0002_auto_20170404_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='gps_x',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
